/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118013-g7b73ea501d-20241205"
#endif /* AVUTIL_FFVERSION_H */
